name: DCA Weekdays (Upbit)

on:
  schedule:
    - cron: "0 1 * * 1-5"  # UTC 01:00 = KST 10:00, 평일만
  workflow_dispatch: {}

env:
  TARGET_HOUR_KST: "10"
  STRICT_TIME_ONLY: "true"
  WINDOW_MINUTES: "30"       # 여기서도 동일하게 30분 설정
  DAILY_BUDGET_KRW: "40000"
  UPBIT_KRW_FEE: "0.0005"
  UPBIT_MIN_ORDER_KRW: "5000"
  DCA_PAUSE: "0"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests tzdata pyjwt

      - name: Run DCA bot
        env:
          UPBIT_ACCESS_KEY: ${{ secrets.UPBIT_ACCESS_KEY }}
          UPBIT_SECRET_KEY: ${{ secrets.UPBIT_SECRET_KEY }}
          TARGET_HOUR_KST: ${{ env.TARGET_HOUR_KST }}
          STRICT_TIME_ONLY: ${{ env.STRICT_TIME_ONLY }}
          WINDOW_MINUTES: ${{ env.WINDOW_MINUTES }}
          DAILY_BUDGET_KRW: ${{ env.DAILY_BUDGET_KRW }}
          UPBIT_KRW_FEE: ${{ env.UPBIT_KRW_FEE }}
          UPBIT_MIN_ORDER_KRW: ${{ env.UPBIT_MIN_ORDER_KRW }}
          DCA_PAUSE: ${{ env.DCA_PAUSE }}
        run: |
          python upbit_noon_weekday_dca.py

  notify:
    name: Notify Telegram
    needs: [run]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        id: mk
        shell: bash
        run: |
          if [ "${{ needs.run.result }}" = "success" ]; then
            STATUS="✅ SUCCESS"
          else
            STATUS="❌ FAILURE"
          fi
          MSG="[${GITHUB_REPOSITORY}] ${{ github.workflow }} #${{ github.run_number }} → ${STATUS}\nEvent: ${{ github.event_name }}\nBranch: ${{ github.ref_name }}\nActor: ${{ github.actor }}\nURL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "msg=${MSG}" >> "$GITHUB_OUTPUT"

      - name: Send Telegram
        env:
          TOKEN:   ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TEXT:    ${{ steps.mk.outputs.msg }}
        run: |
          curl -s "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            --data-urlencode "chat_id=${CHAT_ID}" \
            --data-urlencode "text=${TEXT}"
